id = '220338999523409921' # server ID 220343370411802626','220348641913602048','317681753508806666','313868758982590464','271064369796743169','487327606698409986
token = 'NTAwNzcwMjc1MDk3MzEzMjkw.DqVVpg.XPz4XAKaoWz9a9eJD6DjoIn4Z_U' # bot token
whitelist = ['220441635622879232','220343370411802626','220348641913602048','317681753508806666','313868758982590464','271064369796743169','487327606698409986','313725364226621442',] # list of channels to post to first one is #social
messages = [
        '@here this is a public service announcement that ahm still in jail... I still need one of yalll to bail me out....plz',
        'one day I farted and it hurt really bad. Till this day Im trying to figure out why. Ill update yall when I figure it out',
        'I be readin the feedback for Ray Fox sometimes. who yamcha is? and why am I compared to him so much? Is he cool?',
        'yall need to remind Scotty to make mo Monkey hoes for me. I be at the club with the gang and they never be no monkey females there. What about me man? even Tang get his fine scalies this aint fair. I mean I cant get to the club now I guess since ahm still in jail... but cmon. Make some monkeys by the time I get out, you got time.',
        'ahm still in jail. lets make a free boony campain',
        'My hair looks like an orange star. ***** s love stars',
        'my comb broke the other day'
        'dnator and viint are my biggest fans I think. If yoall really love me yall bail me out...',
        '**** Ray',
        'the guys in here be lookin at me funny sometimes',
        'free boony',
        'yall ever heard of Aggsutko? theres this gorrilla chick named gori thats pretty fine. I heard yall be into that furry manynga stuff or whateveuh. Yall should give me her numbuh',
        'is cat callin still offensive if im hollarin at a sexy feline?'
        'theres too many rules in society man I should not be in jail. I did nothin rong',
        'ahm the coolest character in the comic, yall just dont know it',
        'ahm still in jail, yall',
        'how am I talkin to yall through this thing anyway? Im still in jail right?',
        'when I get out the pen im gonna use that pictuh of me on the front covuh of the comic as my twitter avatuh. someone here told me im photogenik',
        'the crew be makin fun of me but they dont know I got fans. Who cares about Halberd anyway. I bet yall dont know who Tang is and Wasp is a little *****',
        'someone at the pen told me I need Jesus and I told him he need Jesus too because why we both here then? Get out my face with that bullcrap. got him',
        'they take my phone away from me sometimes but I get it. I be on some bull sometimes. Idk why they be lettin me talk anyway. Important character privelage?',
        'some guy at da pen got mad cuz I told im I like justice league movie. Yes. da movie. Stop judging me',
        'scotty wants me to be stop bein on my bull and promote the comic. he said he can shorten my sentence if I tell yall to the read the comic. I hope he aint lyin',
        'yall probably wondering how I got the name boony. its my nick name but I forgot why Hal calls me that.. I just liked it y know',
        'shout outs to gaboris for helpin me talk to yall. now all I need is for him to bail me out too!',
        'I dont know how yall be playing games all day. everybody be on bull. I used to play tekken a lot. I was really good at it. But everyone was pissing me off. they was always quittin when I win then say mean things to me. All I said was his mama raised a ***** for getting whooped so bad. Anyway, I dont be playing games no mo ever since',
        'yall like my cigar? I like it. They took it away from me when I got arrested.',
        'I hope halberd is in jail longer than me. he be pissin me off',
        'ahm a godlen tamarin incase yall was wondering. im a good lookin monkey and dont yall forget it.',
        'it be so borin in here sometimes',
        'get me out of jail plz',
        'Scotty told me that yall like me a lot so I should be in the comic again soon. but at this rate, Ill be in here for years! we need more artists or somthin',
        'I used to think my farts were funny until I dated a tamarin who farted and it smelled like sin. She thought it was funny but I was confused. I went home sad and thought to myself is this how I be? do I need to change',
        'mario party is dat thang',
        'if tang wasnt so stupid we woulda beat Blaze on the first page',
        'my favorite rapper is ELL. man she fine.. when I get outta jail I needa hook up',
        'i read chapter 2 and liev lost to Ray too.. sorta. anyway! SEE, it aint that easy ya bum!',
        'I aint as dirty as yall think I am. theres a reason the monkeys like me. I keep my fur on deck wit da cleanest shampoo my boi',
        'bug scotty to draw me mo. specifically with the finest tamarin in the da club',
        'before ah went to prison what me and da gang did was steal weapons. its a good gig. I aint do nuthin wrong. we take the weapons from govment. I thought yall hated guns and stuff that technically means im on yall side right?',
        'I got into yet another fight in the pen. he was another monkey. I told him I prefer tamarins he said all monkeys are beautiful, even baboons but that last part set me off..',
        'I win all the fights I get into in here. you think I could be like kingpin one day? Thats it. Ill start my OWN gang and take out Liev and the syndicate myself. All monkeys',
        'theres this one dude out heah thats like a hunid years old STILL workin at the pen. Always hyper and ****. always screamin at me. He be pissin me off. nobody got time fo dat',
        'get me out of heah',
        'one of the dudes here told me about this thang called memes for like 3 hours and it got me thinkin.. am I a meme?',
        'sometimes I be glad ahm in jail. free food and winning fights every day beats browsin twitter',
        'i played this mobile game one time and it was really borin',
        'I giant bunion on my foot for wearing dem dang shoes in the firt chapter. ahm glad scotty got rid of that because this hurts like sin..',
        'if I ever see Hal again, we aint friends no mo. ahm startin mah own gang. all monkeys. AND ahm getting a fine tamarin in there too.',
        'lion tamrin thighs save lives.',
        'ah need someone to rub mah back.',
    ] # list of possible messages
time_min = 18000 # minimum seconds till next post
time_max = 259200 # maximum seconds till next post
